### ISSUE TITLE
Does this work on android as well?

### ISSUE THREAD

**Issue by claykohut** [promptworks/ignite-action-extension-example#1]
Any way you could add some extra instructions on the android side of things?

Thanks,
Clay

**Comment by patricksmith** [comment]
Hi Clay,

Unfortunately, this repo only deals with creating the action extension on the iOS side of things. For Android, there appear to be [some packages](https://www.npmjs.com/package/react-native-share-menu) available to add a share extension, which isn't quite the same as an action extension on iOS. 

Our use case was only concerned with an iOS action extension, so I'm afraid I can't be very helpful, sorry. If you've found a way to get it working on Android, I'd be curious to hear about it!
